### ISSUE TITLE
Continue Mode Issues

### ISSUE THREAD

**Issue by spenjer1** [fross123/csv_to_qlab#105]
**Describe the bug**
`Continue Mode` `continueMode` and `Follow` are mentioned within the example CSV's, however none of them appear to be working. I'm unsure which one to use when defining Continue Mode with QLab v5. Also, when changing the CSV header row to `Follow` the program gives me an "Internal Server Error".
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application
```
I am using OSX v12 of CSV-to-QLab application.

**To Reproduce**
Below is the CSV I am trying to import

Type | Number | Name | Notes | Fade Opacity | Stop Target when Done | Follow | Target | File Target | Color | Network Patch Number | Custom String
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
network | 1 | Network 0-0-1 | Network Cue 1 |   |   | 0 |   |   |   | 1 | /location/0/0/1/press
audio | 2 | Audio Cue | Audio Cue 1 |   |   | 2 |   |   |   |   |  
group | 3 | Audio Group | Walk on track |   |   | 1 |   |   |   |   |  
video | 3.1 | Video Cue | video cue for wlak on | 0 |   | 1 |   |   |   |   |  
fade | 3.2 | Fade Cue 1 | Fade up walkon track | 1 | false | 1 | 3.1 |   |   |   |  
fade | 3.3 | Fade Cue 2 | fade down walkon | 0 | true | 0 | 3.1 |   |   |   |  

**Screenshots**
Internal Server Error - https://imgur.com/pufLeV6

**Desktop (please complete the following information):**
 - OS: OSX 12.3

Any help would be appreciated. Thanks for your hard work on this app - it's great!

**Comment by fross123** [comment]
Hi there @spenjer1 ,

Glad you're interested in using this tool!

To address your first question:
Follow, Continue Mode, ContinueMode, ConTinUEMode, etc... should all work. I don't remember exactly why I originally called it "follow", but it should be interchangeable if you are on a current version. I'll make a note to update the docs, my apologies for the confusing documentation.

I went ahead and tested your csv and was able to successfully import the cues and data as listed.

I'll do some more digging, I have to find a mac with macos12 to run it on... Since I wasn't able to reproduce the issue, I have a few follow up questions/ideas.

- Are any cues successfully sent? Or is the error right away?
- Are you using the localhost ip (127.0.0.1) or the ip of the device on your network?
- How are you creating and saving the csv file?

Let me know when you have a moment. Thank you very much for reporting this issue so we can get to the bottom of this.
Fin

**Comment by fross123** [comment]
@spenjer1 you can disregard my last note, I think I know what happened... My apologies, this was a bug I fixed (which is why it didn't show up when I ran it myself), and I just never published a release. Let me push a new release tonight. You should be able to re-download and it will work.

**Comment by spenjer1** [comment]
Was just checking my messages and writing back. Appreciate the quick response... Glad to know it wasn't just me! I'll redownload when the new version is pushed.

Answering the questions above regardless:

> All cues successfully sent, just not with the "fade" marker
> Yes, using 127.0.0.1
> Generated in Google Sheets, downloaded as CSV. Adjusted some of the text within in TextEditor (formatting removed) to test different variables. 

Everything was working properly except for the continue mode variables within cues. Thanks again for looking into this and resolving.
